### ISSUE TITLE
Get project running under AppVeyor

### ISSUE THREAD

**Issue by aaronmell** [aaronmell/dotnetNES#4]
Will probably need some work to get the integration tests running

**Comment by aaronmell** [comment]
I think I will need to take care of this one.

**Comment by MetaFight** [comment]
It's kind of creepy that we have the same avatar, but I'll ignore that for now.

I was just wondering:  Why Travis and not Appveyor?

IIRC, Travis' support for C# is community-driven and uses mono in Linux.  Appveyor has proper .NET support.

**Comment by aaronmell** [comment]
Didn't know about Appveyor, will take a look at it

**Comment by aaronmell** [comment]
Looks good, going to switch it

**Comment by glennsarti** [comment]
Got the tests running on Appveyor very simply however, the test setup configuration is lacking.  Getting the following errors both on Appveyor and on my local computer

Any ideas what's going on? My knowledge of nunit is basic at best.

```
C:\Source\dotnetNES [add-appveyor +2 ~1 -0 !]> nunit3-console "C:\Source\dotnetNES\dotnetNES.Tests\bin\Debug\dotnetNES.Tests.dll" --trace=debug --labels=all
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Source\dotnetNES\dotnetNES.Tests\bin\Debug\dotnetNES.Tests.dll

=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Misc_No_Errors("01-abs_x_wrap.nes","\n01-abs_x_wrap\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Misc_No_Errors("02-branch_wrap.nes","\n02-branch_wrap\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Test_No_Errors("01-basics.nes","\n01-basics\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Test_No_Errors("10-branches.nes","\n10-branches\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Test_No_Errors("11-stack.nes","\n11-stack\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Test_No_Errors("12-jmp_jsr.nes","\n12-jmp_jsr\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Test_No_Errors("13-rts.nes","\n13-rts\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Test_No_Errors("14-rti.nes","\n14-rti\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Test_No_Errors("15-brk.nes","\n15-brk\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.CPU_Instruction_Test_No_Errors("16-special.nes","\n16-special\n\nPassed\n\0")
=> dotnetNES.Tests.Processors.CPUTests.Nestest_Matches

Errors, Failures and Warnings

1) Error :
An existing connection was forcibly closed by the remote host

Server stack trace:
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-10-03 04:42:47Z
    End time: 2017-10-03 04:42:58Z
    Duration: 10.690 seconds

Results (nunit3) saved as TestResult.xml

No connection could be made because the target machine actively refused it 127.0.0.1:49736
Failed to stop the remote agent. No connection could be made because the target machine actively refused it 127.0.0.1:49736
C:\Source\dotnetNES [add-appveyor +2 ~1 -0 !]>
```

**Comment by glennsarti** [comment]
I have appveyor running on my fork. https://ci.appveyor.com/project/glennsarti/dotnetnes

**Comment by aaronmell** [comment]
Not sure what the issue is.

**Comment by aaronmell** [comment]
found a link to that error 

https://github.com/nunit/nunit/issues/736

I know there are failing tests, maybe a test is failing in a way that is causing nunit to fail.

**Comment by glennsarti** [comment]
Possibly.  It's interesting that it fails rather forcefully

```
Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
```

**Comment by aaronmell** [comment]
building the vNext branch and tests are failing but running. 

https://ci.appveyor.com/project/aaronmell/dotnetnes

**Comment by glennsarti** [comment]
Interesting...I might try cherry picking some commits over (in particular the psake file and nlog config)...  But the move to .Net 4.6.1 may also have helped.

**Comment by glennsarti** [comment]
Oh and the major version bump in NUnit too  2.6 to 3.0

**Comment by glennsarti** [comment]
Do you intend to merge vNext into master soon?

**Comment by aaronmell** [comment]
No, I'm going to continue to work on vNext until I finish the sprite handling
